base:
  source link: https://replit.com/@ENIAC1/NameForums-v2
  profile link: https://replit.com/@ENIAC1
  version: 0.13

website:
  name: Stachums
  email: eniteam@outlook.com

email:
  shortname: SUms